### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by Arjun31415** [M-Manas-s/MP#1]
Pasting the RAW code into a text file and running with MASM gives error

**Comment by Arjun31415** [comment]
please resolve this issue. Need it code paint in assembly 😂

**Comment by Arjun31415** [comment]
Please fix asap

**Comment by Arjun31415** [comment]
Bump

**Comment by AlvinManojAlex** [comment]
Why Arjun are you not going for simple code that makes our assembly life easier?

**Comment by M-Manas-s** [comment]
Hi @Arjun31415 ,
        Our team of Engineers went through the issue and after careful consideration we came to the conclusion that the code works perfectly fine and also that you are geyh. We will be looking forward to your contributions in this repository.
Happy Coding!

**Comment by Arjun31415** [comment]
> Hi @Arjun31415 ,
>         Our team of Engineers went through the issue and after careful consideration we came to the conclusion that the code works perfectly fine and also that you are geyh. We will be looking forward to your contributions in this repository.
> Happy Coding!

That is very derogatory. 😞😔

**Comment by Arjun31415** [comment]
I will be reporting this repository to GitHub very unprofessional behaviour

**Comment by M-Manas-s** [comment]
Do as you must, for I have already won.

> I will be reporting this repository to GitHub very unprofessional behaviour

**Comment by AlvinManojAlex** [comment]
> Do what you must, for I have already won.
> 
> > I will be reporting this repository to GitHub very unprofessional behaviour

Might I just remind that the issue here is "Code error" and not some sort of behavioral error 😃

**Comment by M-Manas-s** [comment]
> > Do what you must, for I have already won.
> > > I will be reporting this repository to GitHub very unprofessional behaviour
> 
> Might I just remind that the issue here is "Code error" and not some sort of behavioral error smiley

Yes @AlvinManojAlex we understand your concern. The issue has been resolved and will be closed within a few days.

**Comment by Arjun31415** [comment]
Then fix the error for god's sake
instead of doing this thing

**Comment by AlvinManojAlex** [comment]
> Yes @AlvinManojAlex we understand your concern. The issue has been resolved and will be closed within a few days.

Thats good to know
And @Arjun31415.. Thanks for your contribution 😃

**Comment by Arjun31415** [comment]
> > > Do what you must, for I have already won.
> > > > I will be reporting this repository to GitHub very unprofessional behaviour
> > 
> > 
> > Might I just remind that the issue here is "Code error" and not some sort of behavioral error smiley
> 
> Yes @AlvinManojAlex we understand your concern. The issue has been resolved and will be closed within a few days.

No it is not resolved 
it still gives errors

**Comment by M-Manas-s** [comment]
> > > > Do what you must, for I have already won.
> > > > > I will be reporting this repository to GitHub very unprofessional behaviour
> > > 
> > > 
> > > Might I just remind that the issue here is "Code error" and not some sort of behavioral error smiley
> > 
> > 
> > Yes @AlvinManojAlex we understand your concern. The issue has been resolved and will be closed within a few days.
> 
> No it is not resolved it still gives errors

It has been fixed plus you are banned from speaking. Closing the issue. Thank you for your contributions.
