### ISSUE TITLE
Code Error #3

### ISSUE THREAD

**Issue by Arjun31415** [M-Manas-s/MP#3]
please fix the raw codes. It does not work

**Comment by AlvinManojAlex** [comment]
@Arjun31415 git good 😆

**Comment by Arjun31415** [comment]
> @Arjun31415 git good laughing

go away I just want better asm codes

**Comment by AlvinManojAlex** [comment]
@Arjun31415 chi assembly codes.. git good

**Comment by M-Manas-s** [comment]
Why are you ... ?
